export const FETCH_DATA_REQUEST = "FETCH_DATA";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";
export const FETCH_ASSETS_REQUEST = "FETCH_ASSETS";
export const FETCH_ASSETS_SUCCESS = "FETCH_ASSETS_SUCCESS";
export const FETCH_ASSETS_FAIL = "FETCH_ASSETS_FAIL";
export const FETCH_ASSET_REQUEST = "FETCH_ASSET";
export const FETCH_ASSET_SUCCESS = "FETCH_ASSET_SUCCESS";
export const FETCH_ASSET_FAIL = "FETCH_ASSET_FAIL";

