export const FETCH_ALL_WORK_REQUEST = "FETCH_ALL_WORK";
export const FETCH_ALL_WORK_SUCCESS = "FETCH_ALL_WORK_SUCCESS";
export const FETCH_ALL_WORK_FAIL = "FETCH_ALL_WORK_FAIL";
export const FETCH_WORK_REQUEST = "FETCH_WORK";
export const FETCH_WORK_SUCCESS = "FETCH_WORK_SUCCESS";
export const FETCH_WORK_FAIL = "FETCH_WORK_FAIL";

