export const FETCH_UNITS_REQUEST = "FETCH_UNITS";
export const FETCH_UNITS_SUCCESS = "FETCH_UNITS_SUCCESS";
export const FETCH_UNITS_FAIL = "FETCH_UNITS_FAIL";
export const FETCH_UNIT_REQUEST = "FETCH_UNIT";
export const FETCH_UNIT_SUCCESS = "FETCH_UNIT_SUCCESS";
export const FETCH_UNIT_FAIL = "FETCH_UNIT_FAIL";

